---
- name: Install and Configure Nginx
  hosts: all
  become: yes  # Run as sudo
  tasks:
    - name: Install Nginx on Debian-based systems
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx on RHEL-based systems
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and Enable Nginx Service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Custom Nginx Configuration
      copy:
        src: files/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
